spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: lb://cities-service
          uri: lb://CITIES-SERVICE
          predicates:
            - Path=/cities/**
        - id: lb://hotels-service
          uri: lb://HOTELS-SERVICE
          predicates:
            - Path=/hotels/**

server:
  port: 8080
