spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        -id: hotels-service
        uri: lb://hotels-service
        predicates:
          - Path=/hotels/**
        -id: cities-service
        uri: lb://cities-service
        predicates:
          - Path=/cities/**
     
         

server:
  port: 8080

