server:
  port: 8082

spring:
  application:
    name: cities-service
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/cities_service?serverTimezone=UTC
    username: admin
    password: 123
